package com.gh.mall.mapper;

import com.gh.mall.entity.AdvertiserInfo;
import org.springframework.stereotype.Repository;

@Repository
public interface AdvertiserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertiser_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertiser_info
     *
     * @mbggenerated
     */
    int insert(AdvertiserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertiser_info
     *
     * @mbggenerated
     */
    int insertSelective(AdvertiserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertiser_info
     *
     * @mbggenerated
     */
    AdvertiserInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertiser_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AdvertiserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertiser_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdvertiserInfo record);
}