package com.gh.mall.mapper;

import com.gh.mall.entity.CartInfo;
import org.springframework.stereotype.Repository;

@Repository
public interface CartInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_info
     *
     * @mbggenerated
     */
    int insert(CartInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_info
     *
     * @mbggenerated
     */
    int insertSelective(CartInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_info
     *
     * @mbggenerated
     */
    CartInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CartInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CartInfo record);
}