package com.gh.mall.mapper;

import com.gh.mall.entity.CommentInfo;
import org.springframework.stereotype.Repository;

@Repository
public interface CommentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated
     */
    int insert(CommentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated
     */
    int insertSelective(CommentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated
     */
    CommentInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommentInfo record);
}