package com.gh.mall.mapper;

import com.gh.mall.entity.NxSystemFileInfo;
import org.springframework.stereotype.Repository;

@Repository
public interface NxSystemFileInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nx_system_file_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nx_system_file_info
     *
     * @mbggenerated
     */
    int insert(NxSystemFileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nx_system_file_info
     *
     * @mbggenerated
     */
    int insertSelective(NxSystemFileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nx_system_file_info
     *
     * @mbggenerated
     */
    NxSystemFileInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nx_system_file_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NxSystemFileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nx_system_file_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NxSystemFileInfo record);
}