package com.gh.mall.mapper;

import com.gh.mall.entity.OrderGoodsRel;
import org.springframework.stereotype.Repository;

@Repository
public interface OrderGoodsRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_rel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_rel
     *
     * @mbggenerated
     */
    int insert(OrderGoodsRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_rel
     *
     * @mbggenerated
     */
    int insertSelective(OrderGoodsRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_rel
     *
     * @mbggenerated
     */
    OrderGoodsRel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderGoodsRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderGoodsRel record);
}