package com.gh.mall.mapper;

import com.gh.mall.entity.TypeInfo;
import org.springframework.stereotype.Repository;

@Repository
public interface TypeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated
     */
    int insert(TypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated
     */
    int insertSelective(TypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated
     */
    TypeInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TypeInfo record);
}