package com.gh.mall.entity;

import javax.persistence.*;

@Table(name = "comment_info")
public class CommentInfo {
    /**
     * 主键
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * 评价内容
     */
    @Column(name = "content")
    private String content;

    /**
     * 所属商品
     */
    @Column(name = "goodsId")
    private Long goodsid;

    /**
     * 评价人id
     */
    @Column(name = "userId")
    private Long userid;

    /**
     * 用户等级
     */
    @Column(name = "level")
    private Integer level;

    /**
     * 创建时间
     */
    @Column(name = "createTime")
    private String createtime;

    @Transient
    private String userName;

    @Transient
    private String goodsName;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getGoodsName() {
        return goodsName;
    }

    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_info.id
     *
     * @return the value of comment_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_info.id
     *
     * @param id the value for comment_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_info.content
     *
     * @return the value of comment_info.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_info.content
     *
     * @param content the value for comment_info.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_info.goodsId
     *
     * @return the value of comment_info.goodsId
     *
     * @mbggenerated
     */
    public Long getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_info.goodsId
     *
     * @param goodsid the value for comment_info.goodsId
     *
     * @mbggenerated
     */
    public void setGoodsid(Long goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_info.userId
     *
     * @return the value of comment_info.userId
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_info.userId
     *
     * @param userid the value for comment_info.userId
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_info.level
     *
     * @return the value of comment_info.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_info.level
     *
     * @param level the value for comment_info.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_info.createTime
     *
     * @return the value of comment_info.createTime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_info.createTime
     *
     * @param createtime the value for comment_info.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }
}