package com.gh.mall.entity;

public class OrderGoodsRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods_rel.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods_rel.orderId
     *
     * @mbggenerated
     */
    private Long orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods_rel.goodsId
     *
     * @mbggenerated
     */
    private Long goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods_rel.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_rel.id
     *
     * @return the value of order_goods_rel.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_rel.id
     *
     * @param id the value for order_goods_rel.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_rel.orderId
     *
     * @return the value of order_goods_rel.orderId
     *
     * @mbggenerated
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_rel.orderId
     *
     * @param orderid the value for order_goods_rel.orderId
     *
     * @mbggenerated
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_rel.goodsId
     *
     * @return the value of order_goods_rel.goodsId
     *
     * @mbggenerated
     */
    public Long getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_rel.goodsId
     *
     * @param goodsid the value for order_goods_rel.goodsId
     *
     * @mbggenerated
     */
    public void setGoodsid(Long goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_rel.count
     *
     * @return the value of order_goods_rel.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_rel.count
     *
     * @param count the value for order_goods_rel.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}